exp: exp.cpp 
	g++ exp.cpp  bestfit.cpp bestfitdecreasing.cpp firstfit.cpp firstfitdecreasing.cpp utils.cpp data_generator.cpp -o exp.o

exps: exp.cpp 
	g++ exp_seg_tree.cpp firstfit_segtree.cpp bestfit.cpp bestfitdecreasing.cpp firstfit.cpp firstfitdecreasing.cpp utils.cpp data_generator.cpp -o exps.o


clean: 
	rm -f *.out *.o
